export const FETCH_FRIENDS_REQUEST = 'FRIEND::FETCH_FRIENDS_REQUEST';
export type FETCH_FRIENDS_REQUEST = typeof FETCH_FRIENDS_REQUEST;

export const FETCH_FRIENDS_SUCCESS = 'FRIEND::FETCH_FRIENDS_SUCCESS';
export type FETCH_FRIENDS_SUCCESS = typeof FETCH_FRIENDS_SUCCESS;

export const FETCH_FRIENDS_FAILURE = 'FRIEND::FETCH_FRIENDS_FAILURE';
export type FETCH_FRIENDS_FAILURE = typeof FETCH_FRIENDS_FAILURE;

// TODO: FetchFriendsAbort?
