export const STEAM_FRIENDS_REQUEST = 'FRIEND::STEAM_FRIENDS_REQUEST';
export type STEAM_FRIENDS_REQUEST = typeof STEAM_FRIENDS_REQUEST;

export const STEAM_FRIENDS_RESPONSE = 'FRIEND::STEAM_FRIENDS_RESPONSE';
export type STEAM_FRIENDS_RESPONSE = 'FRIEND::STEAM_FRIENDS_RESPONSE';

export const STEAM_FRIENDS_FAILURE = 'FRIEND::STEAM_FRIENDS_FAILURE';
export type STEAM_FRIENDS_FAILURE = 'FRIEND::STEAM_FRIENDS_FAILURE';

export const SOCKET_FRIENDS_REQUEST = 'FRIEND::SOCKET_FRIENDS_REQUEST';
export type SOCKET_FRIENDS_REQUEST = typeof SOCKET_FRIENDS_REQUEST;

export const SOCKET_FRIENDS_SUCCESS = 'FRIEND::SOCKET_FRIENDS_SUCCESS';
export type SOCKET_FRIENDS_SUCCESS = typeof SOCKET_FRIENDS_SUCCESS;

export const SOCKET_FRIENDS_FAILURE = 'FRIEND::SOCKET_FRIENDS_FAILURE';
export type SOCKET_FRIENDS_FAILURE = typeof SOCKET_FRIENDS_FAILURE;

// TODO: Abort?
