export const STEAM_FRIENDS_REQUEST = 'FRIEND::STEAM_FRIENDS_REQUEST';
export type STEAM_FRIENDS_REQUEST = typeof STEAM_FRIENDS_REQUEST;

export const STEAM_FRIENDS_RESPONSE = 'FRIEND::STEAM_FRIENDS_RESPONSE';
export type STEAM_FRIENDS_RESPONSE = 'FRIEND::STEAM_FRIENDS_RESPONSE';

export const STEAM_FRIENDS_FAILURE = 'FRIEND::STEAM_FRIENDS_FAILURE';
export type STEAM_FRIENDS_FAILURE = 'FRIEND::STEAM_FRIENDS_FAILURE';

export const BACKEND_FRIENDS_REQUEST = 'FRIEND::BACKEND_FRIENDS_REQUEST';
export type BACKEND_FRIENDS_REQUEST = typeof BACKEND_FRIENDS_REQUEST;

export const BACKEND_FRIENDS_SUCCESS = 'FRIEND::BACKEND_FRIENDS_SUCCESS';
export type BACKEND_FRIENDS_SUCCESS = typeof BACKEND_FRIENDS_SUCCESS;

export const BACKEND_FRIENDS_FAILURE = 'FRIEND::BACKEND_FRIENDS_FAILURE';
export type BACKEND_FRIENDS_FAILURE = typeof BACKEND_FRIENDS_FAILURE;

// TODO: Abort?
