export const SET_ACCESS_TOKEN = 'SESSION::SET_ACCESS_TOKEN';
export type SET_ACCESS_TOKEN = typeof SET_ACCESS_TOKEN;

export const SET_PLAYER_NET_ID = 'SESSION::SET_PLAYER_NET_ID';
export type SET_PLAYER_NET_ID = typeof SET_PLAYER_NET_ID;

export const SET_USER_SERIAL = 'SESSION::SET_USER_SERIAL';
export type SET_USER_SERIAL = typeof SET_USER_SERIAL;
