export const WEBSOCKET_INIT = 'WEBSOCKET::INIT';
export type WEBSOCKET_INIT = typeof WEBSOCKET_INIT;

export const WEBSOCKET_READY = 'WEBSOCKET::READY';
export type WEBSOCKET_READY = typeof WEBSOCKET_READY;

export const WEBSOCKET_ERROR = 'WEBSOCKET::ERROR';
export type WEBSOCKET_ERROR = typeof WEBSOCKET_ERROR;

export const WEBSOCKET_CLOSED = 'WEBSOCKET::CLOSED';
export type WEBSOCKET_CLOSED = typeof WEBSOCKET_CLOSED;

export const WEBSOCKET_REQUEST = 'WEBSOCKET::REQUEST';
export type WEBSOCKET_REQUEST = typeof WEBSOCKET_REQUEST;

export const WEBSOCKET_RESPONSE = 'WEBSOCKET::RESPONSE';
export type WEBSOCKET_RESPONSE = typeof WEBSOCKET_RESPONSE;

export const WEBSOCKET_CONNECTED = 'WEBSOCKET::CONNECTED';
export type WEBSOCKET_CONNECTED = typeof WEBSOCKET_CONNECTED;
