export const WEBSOCKET_INIT = 'APP::WEBSOCKET_INIT';
export type WEBSOCKET_INIT = typeof WEBSOCKET_INIT;

export const WEBSOCKET_READY = 'APP::WEBSOCKET_READY';
export type WEBSOCKET_READY = typeof WEBSOCKET_READY;

export const WEBSOCKET_ERROR = 'APP::WEBSOCKET_ERROR';
export type WEBSOCKET_ERROR = typeof WEBSOCKET_ERROR;

export const WEBSOCKET_CLOSED = 'APP::WEBSOCKET_CLOSED';
export type WEBSOCKET_CLOSED = typeof WEBSOCKET_CLOSED;

export const WEBSOCKET_REQUEST = 'APP::WEBSOCKET_REQUEST';
export type WEBSOCKET_REQUEST = typeof WEBSOCKET_REQUEST;

export const WEBSOCKET_RESPONSE = 'APP::WEBSOCKET_RESPONSE';
export type WEBSOCKET_RESPONSE = typeof WEBSOCKET_RESPONSE;

export const WEBSOCKET_CONNECTED = 'APP::WEBSOCKET_CONNECTED';
export type WEBSOCKET_CONNECTED = typeof WEBSOCKET_CONNECTED;
