export const TOGGLE_READY = 'MATCHMAKE::TOGGLE_READY';
export type TOGGLE_READY = typeof TOGGLE_READY;

export const QUEUE_START = 'MATCHMAKE::QUEUE_START';
export type QUEUE_START = typeof QUEUE_START;

export const QUEUE_CANCEL = 'MATCHMAKE::QUEUE_CANCEL';
export type QUEUE_CANCEL = typeof QUEUE_CANCEL;

export const QUEUE_ERROR = 'MATCHMAKE::QUEUE_ERROR';
export type QUEUE_ERROR = typeof QUEUE_ERROR;
