export const APP_INITIALIZE = 'APP::INITIALIZE';
export type APP_INITIALIZE = typeof APP_INITIALIZE;

// When engine is ready to take calls
export const ENGINE_READY = 'APP::ENGINE_READY';
export type ENGINE_READY = typeof ENGINE_READY;

// AUTHENTICATION
export const AUTH_REQUEST = 'APP::AUTH_REQUEST';
export type AUTH_REQUEST = typeof AUTH_REQUEST;

export const AUTH_SUCCESS = 'APP::AUTH_SUCCESS';
export type AUTH_SUCCESS = typeof AUTH_SUCCESS;

// TODO: This is not currently in use.
export const AUTH_FAILURE = 'APP::AUTH_FAILURE';
export type AUTH_FAILURE = typeof AUTH_FAILURE;

// COUNTRY CODE
export const COUNTRY_CODE_REQUEST = 'SESSION::COUNTRY_CODE_REQUEST';
export type COUNTRY_CODE_REQUEST = typeof COUNTRY_CODE_REQUEST;

export const COUNTRY_CODE_SUCCESS = 'SESSION::COUNTRY_CODE_SUCCESS';
export type COUNTRY_CODE_SUCCESS = typeof COUNTRY_CODE_SUCCESS;

// VERSIONING
export const VERSION_REQUEST = 'APP::VERSION_REQUEST';
export type VERSION_REQUEST = typeof VERSION_REQUEST;

export const VERSION_SUCCESS = 'APP::VERSION_SUCCESS';
export type VERSION_SUCCESS = typeof VERSION_SUCCESS;

// WEBSOCKETS
export const WEBSOCKET_INIT = 'APP::WEBSOCKET_INIT';
export type WEBSOCKET_INIT = typeof WEBSOCKET_INIT;

export const WEBSOCKET_READY = 'APP::WEBSOCKET_READY';
export type WEBSOCKET_READY = typeof WEBSOCKET_READY;

export const WEBSOCKET_ERROR = 'APP::WEBSOCKET_ERROR';
export type WEBSOCKET_ERROR = typeof WEBSOCKET_ERROR;

export const WEBSOCKET_CLOSED = 'APP::WEBSOCKET_CLOSED';
export type WEBSOCKET_CLOSED = typeof WEBSOCKET_CLOSED;

export const WEBSOCKET_REQUEST = 'APP::WEBSOCKET_REQUEST';
export type WEBSOCKET_REQUEST = typeof WEBSOCKET_REQUEST;

export const WEBSOCKET_RESPONSE = 'APP::WEBSOCKET_RESPONSE';
export type WEBSOCKET_RESPONSE = typeof WEBSOCKET_RESPONSE;

export const WEBSOCKET_CONNECTED = 'APP::WEBSOCKET_CONNECTED';
export type WEBSOCKET_CONNECTED = typeof WEBSOCKET_CONNECTED;
